from __future__ import annotations
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / "data"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
TRACKS_CLEANED_PATH = PROCESSED_DATA_DIR / "tracks_cleaned.csv"
USER_INTERACTIONS_PATH = PROCESSED_DATA_DIR / "user_interactions.csv"
GENRE_ENCODER_PATH = PROCESSED_DATA_DIR / "genre_encoder.pkl"
ARTIST_ENCODER_PATH = PROCESSED_DATA_DIR / "artist_encoder.pkl"
FEATURE_SCALER_PATH = PROCESSED_DATA_DIR / "feature_scaler.pkl"

MODEL_DIR = ROOT_DIR / "models"
TWO_TOWER_MODEL_PATH = MODEL_DIR / "two_tower.pth"
LIGHTGCN_MODEL_PATH = MODEL_DIR / "lightgcn.pth"
RANKING_MODEL_PATH = MODEL_DIR / "ranking_mtl.pth"
EMBEDDING_MODEL_PATH = MODEL_DIR / "embedding_model.pth"
RETRIEVAL_MODEL_PATH = MODEL_DIR / "retrieval_model.pth"
FAISS_INDEX_DIR = MODEL_DIR / "faiss"
# keep legacy path expectations for tests: put faiss index at models/faiss_index.bin by default
FAISS_INDEX_PATH = MODEL_DIR / "faiss_index.bin"
# track ids mapping default (legacy location at models/track_ids.pkl)
FAISS_TRACK_IDS_PATH = MODEL_DIR / "track_ids.pkl"

# Defaults and numeric configuration
DEFAULT_SEARCH_LIMIT = 20
MAX_SEARCH_RESULTS = 50
SEARCH_SCORE_THRESHOLD = 45
CORRECTION_SCORE_THRESHOLD = 80
EMBEDDING_DIMENSION = 128
RETRIEVAL_TOP_K = 20
RETRIEVAL_CANDIDATE_LIMIT = 500
RECOMMENDATION_TOP_K = 20
SEARCH_MAX_RESULTS = 50

# High-level feature flags and runtime options (backward-compatible defaults)
AUTO_LOAD_MODELS = True
AUTO_LOAD_FAISS = True
ENABLE_FAISS = True
ENABLE_TWOTOWER = True
ENABLE_LIGHTGCN = True
EMBEDDING_CACHE_SIZE = None  # optional limit for caching (bytes), None = unlimited

# Legacy aliases kept for compatibility
EMBEDDING_MODEL_PATH = TWO_TOWER_MODEL_PATH
RETRIEVAL_MODEL_PATH = LIGHTGCN_MODEL_PATH


class Config:
    ROOT_DIR = ROOT_DIR
    DATA_DIR = DATA_DIR
    PROCESSED_DATA_DIR = PROCESSED_DATA_DIR
    TRACKS_CLEANED_PATH = TRACKS_CLEANED_PATH
    USER_INTERACTIONS_PATH = USER_INTERACTIONS_PATH
    GENRE_ENCODER_PATH = GENRE_ENCODER_PATH
    ARTIST_ENCODER_PATH = ARTIST_ENCODER_PATH
    FEATURE_SCALER_PATH = FEATURE_SCALER_PATH

    MODEL_DIR = MODEL_DIR
    TWO_TOWER_MODEL_PATH = TWO_TOWER_MODEL_PATH
    LIGHTGCN_MODEL_PATH = LIGHTGCN_MODEL_PATH
    RANKING_MODEL_PATH = RANKING_MODEL_PATH

    FAISS_INDEX_DIR = FAISS_INDEX_DIR
    FAISS_INDEX_PATH = FAISS_INDEX_PATH
    FAISS_TRACK_IDS_PATH = FAISS_TRACK_IDS_PATH

    # Runtime flags
    AUTO_LOAD_MODELS = AUTO_LOAD_MODELS
    AUTO_LOAD_FAISS = AUTO_LOAD_FAISS
    ENABLE_FAISS = ENABLE_FAISS
    ENABLE_TWOTOWER = ENABLE_TWOTOWER
    ENABLE_LIGHTGCN = ENABLE_LIGHTGCN
    EMBEDDING_CACHE_SIZE = EMBEDDING_CACHE_SIZE

    # Numeric defaults
    DEFAULT_SEARCH_LIMIT = DEFAULT_SEARCH_LIMIT
    MAX_SEARCH_RESULTS = MAX_SEARCH_RESULTS
    SEARCH_SCORE_THRESHOLD = SEARCH_SCORE_THRESHOLD
    CORRECTION_SCORE_THRESHOLD = CORRECTION_SCORE_THRESHOLD
    EMBEDDING_DIMENSION = EMBEDDING_DIMENSION
    RETRIEVAL_TOP_K = RETRIEVAL_TOP_K
    RETRIEVAL_CANDIDATE_LIMIT = RETRIEVAL_CANDIDATE_LIMIT
    RECOMMENDATION_TOP_K = RECOMMENDATION_TOP_K
    SEARCH_MAX_RESULTS = SEARCH_MAX_RESULTS

    # Backward-compatible aliases
    EMBEDDING_MODEL_PATH = EMBEDDING_MODEL_PATH
    RETRIEVAL_MODEL_PATH = RETRIEVAL_MODEL_PATH
