from __future__ import annotations
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / "data"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
TRACKS_CLEANED_PATH = PROCESSED_DATA_DIR / "tracks_cleaned.csv"
USER_INTERACTIONS_PATH = PROCESSED_DATA_DIR / "user_interactions.csv"
GENRE_ENCODER_PATH = PROCESSED_DATA_DIR / "genre_encoder.pkl"
ARTIST_ENCODER_PATH = PROCESSED_DATA_DIR / "artist_encoder.pkl"
FEATURE_SCALER_PATH = PROCESSED_DATA_DIR / "feature_scaler.pkl"

MODEL_DIR = ROOT_DIR / "models"
TWO_TOWER_MODEL_PATH = MODEL_DIR / "two_tower.pth"
LIGHTGCN_MODEL_PATH = MODEL_DIR / "lightgcn.pth"
RANKING_MODEL_PATH = MODEL_DIR / "ranking_mtl.pth"
FAISS_INDEX_DIR = MODEL_DIR / "faiss"
FAISS_INDEX_PATH = FAISS_INDEX_DIR / "faiss_index.bin"
FAISS_TRACK_IDS_PATH = FAISS_INDEX_DIR / "track_ids.pkl"

DEFAULT_SEARCH_LIMIT = 20
MAX_SEARCH_RESULTS = 50
SEARCH_SCORE_THRESHOLD = 45
CORRECTION_SCORE_THRESHOLD = 80
EMBEDDING_DIMENSION = 128
RETRIEVAL_TOP_K = 20
RETRIEVAL_CANDIDATE_LIMIT = 500
RECOMMENDATION_TOP_K = 20
SEARCH_MAX_RESULTS = 50


class Config:
    ROOT_DIR = ROOT_DIR
    DATA_DIR = DATA_DIR
    PROCESSED_DATA_DIR = PROCESSED_DATA_DIR
    TRACKS_CLEANED_PATH = TRACKS_CLEANED_PATH
    GENRE_ENCODER_PATH = GENRE_ENCODER_PATH
    ARTIST_ENCODER_PATH = ARTIST_ENCODER_PATH
    FEATURE_SCALER_PATH = FEATURE_SCALER_PATH
    MODEL_DIR = MODEL_DIR
    EMBEDDING_MODEL_PATH = EMBEDDING_MODEL_PATH
    RETRIEVAL_MODEL_PATH = RETRIEVAL_MODEL_PATH
    FAISS_INDEX_PATH = FAISS_INDEX_PATH
    DEFAULT_SEARCH_LIMIT = DEFAULT_SEARCH_LIMIT
    MAX_SEARCH_RESULTS = MAX_SEARCH_RESULTS
    SEARCH_SCORE_THRESHOLD = SEARCH_SCORE_THRESHOLD
    CORRECTION_SCORE_THRESHOLD = CORRECTION_SCORE_THRESHOLD
    EMBEDDING_DIMENSION = EMBEDDING_DIMENSION
    RETRIEVAL_TOP_K = RETRIEVAL_TOP_K
